version: '3'
services:
  django:
    container_name: fwbm_django
    build: 
      context: ..
      dockerfile: ./docker/django/Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ../django:/app
  
  db:
    container_name: fwbm_db
    build:
      context: ..
      dockerfile: ./docker/postgres/Dockerfile
    restart: unless-stopped
    volumes:
      - ../volumes/dbStorage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "fwbm"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5435:5432

  dotnet:
    container_name: fwbm_dotnet
    build:
      context: ..
      dockerfile: ./docker/dotnet/Dockerfile.dev
    ports:
      - 5028:80
    command: [ "sleep", '999999999999' ]